### PR TITLE
Implementation of multiple image formats and recursive search option

### PR DESCRIPTION
**Pull request by petvetbr**
Hi Steve,

I added the options for .BMP, .JPG, .PNG and .TIF/TIFF and also the option for a recursive search (using -s) in the argument directory.

Thanks,

Fernando

### CODE REVIEW

**Comment by stevedesmond-ca** [comment]
Awesome, thanks -- hopefully will get the chance to merge this soon, but in the meantime, if you get to it first, could you change the -s arg to -r (recursive) since that's more common? Otherwise I'll handle that when I merge it in.

**Comment by petvetbr** [comment]
Sure, I'll send the new version in a few hours.
Em 26/02/2016 13:26, "Steve Desmond" <notifications@github.com> escreveu:

**Comment by stevedesmond-ca** [comment]
thanks again!

**Comment by stevedesmond-ca** [comment]
thanks again!

closes #2

**Pull request merged**
